export type { GetProductsOptions } from './client';
export {
  getAboutUs,
  getBrand,
  getBrands,
  getCategories,
  getCategory,
  getColors,
  getFAQs,
  getHero,
  getProduct,
  getProductBySlug,
  getProducts,
  getProductsByCategory,
  getWhyUs,
} from './client';
export type {
  AboutUsSection,
  Brand,
  Category,
  Color,
  ColorVariant,
  FAQItem,
  HeroSection,
  PaginatedProducts,
  PaginationMeta,
  Product,
  ProductSpec,
  WhyUsFeature,
  WhyUsSection,
} from './types';
